// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCViNtRm9kEowEEJmEcah4vnL22Z0fJMcw',
    appId: '1:623364444953:web:319997ea12ae8dd8d22b88',
    messagingSenderId: '623364444953',
    projectId: 'prestasi-51e6f',
    authDomain: 'prestasi-51e6f.firebaseapp.com',
    storageBucket: 'prestasi-51e6f.firebasestorage.app',
    measurementId: 'G-B3MSTXMNNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWc1zC9Hs0vYv97Y_npOe26V8Ncj0dr0',
    appId: '1:623364444953:android:a8a6576ea358f9e7d22b88',
    messagingSenderId: '623364444953',
    projectId: 'prestasi-51e6f',
    storageBucket: 'prestasi-51e6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1DVyABX46D9qIkxcl_BAJd2b50NeyaBM',
    appId: '1:623364444953:ios:eb6ece65713a36b4d22b88',
    messagingSenderId: '623364444953',
    projectId: 'prestasi-51e6f',
    storageBucket: 'prestasi-51e6f.firebasestorage.app',
    iosClientId: '623364444953-l14jfcr9tg4tjeqopuagfr1ot6husoj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.prestasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1DVyABX46D9qIkxcl_BAJd2b50NeyaBM',
    appId: '1:623364444953:ios:eb6ece65713a36b4d22b88',
    messagingSenderId: '623364444953',
    projectId: 'prestasi-51e6f',
    storageBucket: 'prestasi-51e6f.firebasestorage.app',
    iosClientId: '623364444953-l14jfcr9tg4tjeqopuagfr1ot6husoj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.prestasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCViNtRm9kEowEEJmEcah4vnL22Z0fJMcw',
    appId: '1:623364444953:web:0fb1b89fd9a574b1d22b88',
    messagingSenderId: '623364444953',
    projectId: 'prestasi-51e6f',
    authDomain: 'prestasi-51e6f.firebaseapp.com',
    storageBucket: 'prestasi-51e6f.firebasestorage.app',
    measurementId: 'G-V3HQSZB7YS',
  );
}
